import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
// import Footer from "./components/Footer";
import CursorFollower from "./components/CursorFollower";

// import Background from "./components/Background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">

      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ backgroundImage: 'url("/assets/bg_morph.png")  ' }}
      >
        <CursorFollower />
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
